//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariGuru
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int Id { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Detail1 { get; set; }
        public string Detail2 { get; set; }
        public string Email { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
